# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='OzonPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('deliveryType', models.CharField(max_length=250, verbose_name='deliveryType')),
                ('metro', models.CharField(max_length=250, verbose_name='metro')),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='details',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='features',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='hasDamage',
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(default='', max_length=20, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='url',
            field=models.CharField(default='', max_length=250, verbose_name='url'),
        ),
    ]
