# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190225_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonpoints',
            name='idd',
            field=models.IntegerField(null=True, verbose_name='Id'),
        ),
    ]
