# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ozonpoints_idd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(verbose_name='idd')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
            ],
        ),
    ]
